{% set name = "octokitpy-routes" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0cb58d5d4fa85af6b0d680aca4ff114c9e32919fcb048e8eb6576d48a1d9eecb

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  # Currently can't import specifications on Windows
  # Tracked under issue https://github.com/khornberg/octokitpy-routes/issues/8

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - octokit_routes

about:
  home: https://github.com/khornberg/octokitpy-routes
  license: MIT
  license_family: MIT
  # License file not currently packaged foor routes submodule
  # Issue tracked https://github.com/khornberg/octokitpy-routes/issues/99
  license_file: LICENSE
  summary: Routes for octokitpy
  doc_url: https://octokit.github.io/routes/
  dev_url: https://github.com/khornberg/octokitpy-routes

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
    - ndmaxar
